namespace STS2SkinChanger.Core;

internal static partial class ModLocalization
{
    // Indexed by the contiguous bundle section of ModText; covered by the language contract test.
    private static readonly IReadOnlyDictionary<string, string[]> BundlePacks =
        new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
        {
            ["eng"] = ["Manage skin bundles", "New bundle", "Bundle name", "Character skin", "Card presets", "Monster presets",
                "Unchanged", "Apply", "Saved", "Applied", "Character skin unavailable; using the original skin.",
                "Preset unavailable; skipped: {0}", "Bundle unavailable", "Enter a name of 1–40 characters", "A bundle with this name already exists",
                "Uses existing presets. Choose a [P] bundle in the character skin list; it is applied when the run starts. Later in-run changes do not edit the bundle.", "Save your changes before applying", "Applying…", "These skins require linked changes to other characters or regions. Your settings were left unchanged."],
            ["zhs"] = ["管理皮肤包", "新建皮肤包", "皮肤包名称", "角色皮肤", "卡牌预设", "怪物预设",
                "不修改", "应用", "已保存", "已应用", "角色皮肤不可用，已使用原皮。",
                "预设不可用，已跳过：{0}", "皮肤包不可用", "请输入 1–40 字的名称", "同名皮肤包已存在",
                "引用已有预设。在角色皮肤列表选择 [P] 皮肤包后，点击开始才会应用；局内修改不会改写皮肤包。", "请先保存修改再应用", "正在应用…", "这些皮肤需要联动修改其他角色或地区，无法按本皮肤包的选择应用；原设置未改变。"],
            ["zht"] = ["管理外觀組合包", "新增外觀組合包", "組合包名稱", "角色外觀", "卡牌預設", "怪物預設",
                "不變更", "套用", "已儲存", "已套用", "角色外觀無法使用，已使用原始外觀。",
                "預設無法使用，已略過：{0}", "組合包無法使用", "請輸入 1–40 字的名稱", "同名組合包已存在",
                "引用現有預設。在角色外觀清單選擇 [P] 組合包後，開始遊戲時才會套用；遊戲內變更不會改寫組合包。", "請先儲存變更再套用", "正在套用…", "這些外觀需要連動變更其他角色或地區，無法依此組合包套用；原設定未變更。"],
            ["deu"] = ["Skin-Pakete verwalten", "Neues Paket", "Paketname", "Charakter-Skin", "Kartenvorlagen", "Monstervorlagen",
                "Unverändert", "Anwenden", "Gespeichert", "Angewendet", "Charakter-Skin nicht verfügbar; Original wird verwendet.",
                "Vorlage nicht verfügbar, übersprungen: {0}", "Paket nicht verfügbar", "Namen mit 1–40 Zeichen eingeben", "Ein Paket mit diesem Namen existiert bereits",
                "Verwendet vorhandene Vorlagen. Wähle ein [P]-Paket in der Charakter-Skin-Liste; es wird beim Start des Laufs angewendet. Änderungen im Lauf bearbeiten das Paket nicht.", "Änderungen vor dem Anwenden speichern", "Wird angewendet…", "Diese Skins erfordern verknüpfte Änderungen an anderen Charakteren oder Regionen. Die Einstellungen bleiben unverändert."],
            ["fra"] = ["Gérer les packs d’apparences", "Nouveau pack", "Nom du pack", "Apparence du personnage", "Préréglages de cartes", "Préréglages de monstres",
                "Inchangé", "Appliquer", "Enregistré", "Appliqué", "Apparence indisponible ; apparence d’origine utilisée.",
                "Préréglage indisponible, ignoré : {0}", "Pack indisponible", "Saisissez un nom de 1 à 40 caractères", "Un pack porte déjà ce nom",
                "Utilise les préréglages existants. Choisissez un pack [P] dans la liste des apparences ; il s’applique au début de la partie. Les changements en cours de partie ne modifient pas le pack.", "Enregistrez les changements avant de les appliquer", "Application…", "Ces apparences imposent des changements liés à d’autres personnages ou régions. Vos réglages restent inchangés."],
            ["ita"] = ["Gestisci pacchetti skin", "Nuovo pacchetto", "Nome pacchetto", "Skin personaggio", "Preset carte", "Preset mostri",
                "Invariato", "Applica", "Salvato", "Applicato", "Skin personaggio non disponibile; viene usata l’originale.",
                "Preset non disponibile, ignorato: {0}", "Pacchetto non disponibile", "Inserisci un nome di 1–40 caratteri", "Esiste già un pacchetto con questo nome",
                "Usa i preset esistenti. Scegli un pacchetto [P] nell’elenco skin: verrà applicato all’avvio della partita. Le modifiche durante la partita non cambiano il pacchetto.", "Salva le modifiche prima di applicarle", "Applicazione…", "Queste skin richiedono modifiche collegate ad altri personaggi o regioni. Le impostazioni non sono cambiate."],
            ["jpn"] = ["スキンパック管理", "新規パック", "パック名", "キャラクタースキン", "カードプリセット", "モンスタープリセット",
                "変更しない", "適用", "保存しました", "適用しました", "キャラクタースキンが利用できないため、元のスキンを使用します。",
                "プリセットが利用できないためスキップ：{0}", "パックを利用できません", "1～40文字で名前を入力してください", "同名のパックが既にあります",
                "既存のプリセットを参照します。キャラクタースキン一覧で [P] パックを選ぶと、ラン開始時に適用されます。ラン中の変更はパックを書き換えません。", "適用する前に変更を保存してください", "適用中…", "これらのスキンは他のキャラクターや地域の連動変更が必要なため適用できません。元の設定を維持しました。"],
            ["kor"] = ["스킨 묶음 관리", "새 묶음", "묶음 이름", "캐릭터 스킨", "카드 프리셋", "몬스터 프리셋",
                "변경 안 함", "적용", "저장됨", "적용됨", "캐릭터 스킨을 사용할 수 없어 기본 스킨을 사용합니다.",
                "프리셋을 사용할 수 없어 건너뜀: {0}", "묶음을 사용할 수 없음", "1~40자의 이름을 입력하세요", "같은 이름의 묶음이 있습니다",
                "기존 프리셋을 참조합니다. 캐릭터 스킨 목록에서 [P] 묶음을 선택하면 런 시작 시 적용됩니다. 런 중 변경은 묶음을 수정하지 않습니다.", "적용하기 전에 변경 사항을 저장하세요", "적용 중…", "다른 캐릭터나 지역의 연동 변경이 필요한 스킨입니다. 기존 설정을 유지했습니다."],
            ["pol"] = ["Zarządzaj pakietami skórek", "Nowy pakiet", "Nazwa pakietu", "Skórka postaci", "Presety kart", "Presety potworów",
                "Bez zmian", "Zastosuj", "Zapisano", "Zastosowano", "Skórka postaci niedostępna; użyto oryginalnej.",
                "Preset niedostępny, pominięto: {0}", "Pakiet niedostępny", "Wpisz nazwę od 1 do 40 znaków", "Pakiet o tej nazwie już istnieje",
                "Korzysta z istniejących presetów. Wybierz pakiet [P] na liście skórek postaci; zostanie zastosowany przy rozpoczęciu gry. Zmiany podczas gry nie edytują pakietu.", "Zapisz zmiany przed zastosowaniem", "Stosowanie…", "Te skórki wymagają powiązanych zmian innych postaci lub regionów. Ustawienia pozostały bez zmian."],
            ["ptb"] = ["Gerenciar pacotes de skins", "Novo pacote", "Nome do pacote", "Skin do personagem", "Predefinições de cartas", "Predefinições de monstros",
                "Sem alteração", "Aplicar", "Salvo", "Aplicado", "Skin do personagem indisponível; usando a original.",
                "Predefinição indisponível, ignorada: {0}", "Pacote indisponível", "Digite um nome de 1 a 40 caracteres", "Já existe um pacote com esse nome",
                "Usa predefinições existentes. Escolha um pacote [P] na lista de skins; ele será aplicado ao iniciar a partida. Alterações durante a partida não editam o pacote.", "Salve as alterações antes de aplicar", "Aplicando…", "Estas skins exigem alterações vinculadas a outros personagens ou regiões. As configurações foram mantidas."],
            ["rus"] = ["Управление наборами обликов", "Новый набор", "Название набора", "Облик персонажа", "Пресеты карт", "Пресеты монстров",
                "Не менять", "Применить", "Сохранено", "Применено", "Облик персонажа недоступен; используется оригинальный.",
                "Пресет недоступен, пропущен: {0}", "Набор недоступен", "Введите название длиной 1–40 символов", "Набор с таким названием уже существует",
                "Использует существующие пресеты. Выберите набор [P] в списке обликов; он применится при начале забега. Изменения во время забега не меняют набор.", "Сохраните изменения перед применением", "Применение…", "Эти облики требуют связанных изменений других персонажей или регионов. Настройки не изменены."],
            ["spa"] = ["Gestionar paquetes de aspectos", "Nuevo paquete", "Nombre del paquete", "Aspecto del personaje", "Preajustes de cartas", "Preajustes de monstruos",
                "Sin cambios", "Aplicar", "Guardado", "Aplicado", "Aspecto del personaje no disponible; se usa el original.",
                "Preajuste no disponible, omitido: {0}", "Paquete no disponible", "Introduce un nombre de 1 a 40 caracteres", "Ya existe un paquete con ese nombre",
                "Usa preajustes existentes. Elige un paquete [P] en la lista de aspectos; se aplicará al iniciar la partida. Los cambios durante la partida no modifican el paquete.", "Guarda los cambios antes de aplicarlos", "Aplicando…", "Estos aspectos requieren cambios vinculados en otros personajes o regiones. La configuración no se ha modificado."],
            ["tha"] = ["จัดการชุดสกิน", "ชุดใหม่", "ชื่อชุด", "สกินตัวละคร", "พรีเซ็ตการ์ด", "พรีเซ็ตมอนสเตอร์",
                "ไม่เปลี่ยน", "ใช้", "บันทึกแล้ว", "ใช้แล้ว", "สกินตัวละครไม่พร้อมใช้งาน ใช้สกินเดิมแทน",
                "พรีเซ็ตไม่พร้อมใช้งาน ข้ามแล้ว: {0}", "ชุดไม่พร้อมใช้งาน", "กรอกชื่อ 1–40 ตัวอักษร", "มีชุดชื่อนี้อยู่แล้ว",
                "ใช้พรีเซ็ตที่มีอยู่ เลือกชุด [P] ในรายการสกินตัวละคร แล้วชุดจะถูกใช้เมื่อเริ่มรัน การเปลี่ยนระหว่างรันจะไม่แก้ไขชุด", "บันทึกการเปลี่ยนแปลงก่อนใช้", "กำลังใช้…", "สกินเหล่านี้ต้องเปลี่ยนตัวละครหรือภูมิภาคอื่นร่วมด้วย การตั้งค่าเดิมยังคงอยู่"],
            ["tur"] = ["Görünüm paketlerini yönet", "Yeni paket", "Paket adı", "Karakter görünümü", "Kart ön ayarları", "Canavar ön ayarları",
                "Değiştirme", "Uygula", "Kaydedildi", "Uygulandı", "Karakter görünümü kullanılamıyor; özgün görünüm kullanılıyor.",
                "Ön ayar kullanılamıyor, atlandı: {0}", "Paket kullanılamıyor", "1–40 karakterlik bir ad girin", "Bu adda bir paket zaten var",
                "Mevcut ön ayarları kullanır. Karakter görünümü listesinden bir [P] paketi seçin; koşu başlarken uygulanır. Koşu içindeki değişiklikler paketi düzenlemez.", "Uygulamadan önce değişiklikleri kaydedin", "Uygulanıyor…", "Bu görünümler diğer karakter veya bölgelerde bağlantılı değişiklikler gerektiriyor. Ayarlarınız değiştirilmedi."],
            ["esp"] = ["Gestionar paquetes de aspectos", "Nuevo paquete", "Nombre del paquete", "Aspecto del personaje", "Preajustes de cartas", "Preajustes de monstruos",
                "Sin cambios", "Aplicar", "Guardado", "Aplicado", "Aspecto del personaje no disponible; se usa el original.",
                "Preajuste no disponible, omitido: {0}", "Paquete no disponible", "Introduce un nombre de 1 a 40 caracteres", "Ya existe un paquete con ese nombre",
                "Usa preajustes existentes. Elige un paquete [P] en la lista de aspectos; se aplicará al iniciar la partida. Los cambios durante la partida no modifican el paquete.", "Guarda los cambios antes de aplicarlos", "Aplicando…", "Estos aspectos requieren cambios vinculados en otros personajes o regiones. La configuración no se ha modificado."]
        };
}
