namespace STS2SkinChanger.Core;

internal enum WorkshopNoticeKey
{
    KnownRestart, CheckAfterDownload, RestartTitle, RestartBody, BlockedTitle, BlockedBody,
    Startup, Dependency, Version, UnknownRule, Incomplete, Changed, Duplicate, Invalid, Gameplay
}

internal static class WorkshopNoticeText
{
    private static readonly Dictionary<string, string[]> Packs = new()
    {
        ["zhs"] = "首次加载需重启|下载后检查能否免重启|皮肤需要重启后加载|已订阅：{0}。\n{1}\n请重启游戏后使用。|皮肤暂不可用|已订阅：{0}。\n{1}\n仅重启无法解决，请选择适合当前游戏版本的皮肤。|此皮肤包含需要启动时加载的功能。|前置 Mod 未加载或版本不符，请先安装并启用兼容的前置。|此皮肤要求的游戏版本与当前版本不符。|无法确认此皮肤的版本要求，需要由游戏启动时检查。|无法在本次运行中完整加载此皮肤的全部内容。|已加载的文件发生变化，需重启以避免混用新旧资源。|相同 ID 的 Mod 已存在，需要启动时处理加载关系。|下载文件不完整或格式无法识别，请检查工坊文件；可能需要重新下载。|此 Mod 包含玩法内容，需要在游戏启动时加载。".Split('|'),
        ["zht"] = "首次載入需重新啟動|下載後檢查能否免重啟|皮膚需要重新啟動後載入|已訂閱：{0}。\n{1}\n請重新啟動遊戲後使用。|皮膚暫時無法使用|已訂閱：{0}。\n{1}\n僅重新啟動無法解決，請選擇適合目前遊戲版本的皮膚。|此皮膚包含需要啟動時載入的功能。|前置 Mod 未載入或版本不符，請先安裝並啟用相容的前置。|此皮膚要求的遊戲版本與目前版本不符。|無法確認此皮膚的版本要求，需要由遊戲啟動時檢查。|無法在本次執行中完整載入此皮膚的全部內容。|已載入的檔案發生變化，需重新啟動以避免混用新舊資源。|相同 ID 的 Mod 已存在，需要啟動時處理載入關係。|下載檔案不完整或格式無法識別，請檢查工坊檔案；可能需要重新下載。|此 Mod 包含玩法內容，需要在遊戲啟動時載入。".Split('|'),
        ["eng"] = "Restart needed for first load|Hot-load support checked after download|Restart to load this skin|Subscribed: {0}.\n{1}\nRestart the game before using it.|Skin unavailable|Subscribed: {0}.\n{1}\nRestarting alone will not help. Choose a skin compatible with your game version.|This skin includes features that must load at startup.|A required Mod is not loaded or has an incompatible version. Install and enable a compatible dependency first.|This skin requires a different game version.|The game's startup checks must verify this skin's version requirements.|This skin's full contents cannot be loaded in the current session.|Loaded files have changed. Restart to avoid mixing old and new resources.|A Mod with the same ID already exists; startup must resolve its loading order.|Downloaded files are incomplete or unrecognized. Check the Workshop files; a new download may be needed.|This Mod contains gameplay features that must load at startup.".Split('|'),
        ["deu"] = "Erstladen erfordert Neustart|Hot-Loading wird nach Download geprüft|Neustart zum Laden des Skins|Abonniert: {0}.\n{1}\nStarte das Spiel vor der Verwendung neu.|Skin nicht verfügbar|Abonniert: {0}.\n{1}\nEin Neustart allein hilft nicht. Wähle einen Skin für deine Spielversion.|Dieser Skin enthält Funktionen, die beim Spielstart geladen werden müssen.|Eine benötigte Mod fehlt oder ist inkompatibel. Installiere und aktiviere zuerst eine passende Version.|Dieser Skin benötigt eine andere Spielversion.|Die Versionsanforderungen müssen beim Spielstart geprüft werden.|Dieser Skin kann in dieser Sitzung nicht vollständig geladen werden.|Geladene Dateien wurden geändert. Starte neu, um gemischte Ressourcen zu vermeiden.|Eine Mod mit derselben ID existiert bereits; die Ladereihenfolge muss beim Start geklärt werden.|Dateien sind unvollständig oder unbekannt. Prüfe die Workshop-Dateien; eventuell erneut herunterladen.|Diese Mod enthält Spielfunktionen, die beim Start geladen werden müssen.".Split('|'),
        ["esp"] = "Reinicio necesario al cargar por primera vez|Se comprobará tras descargar|Reinicia para cargar este aspecto|Suscrito: {0}.\n{1}\nReinicia el juego antes de usarlo.|Aspecto no disponible|Suscrito: {0}.\n{1}\nReiniciar no basta. Elige un aspecto compatible con tu versión del juego.|Este aspecto incluye funciones que deben cargarse al iniciar.|Falta un Mod necesario o su versión es incompatible. Instala y activa primero una versión compatible.|Este aspecto requiere otra versión del juego.|Los requisitos de versión deben comprobarse al iniciar el juego.|No se puede cargar todo el contenido del aspecto en esta sesión.|Han cambiado archivos cargados. Reinicia para evitar mezclar recursos antiguos y nuevos.|Ya existe un Mod con el mismo ID; su carga debe resolverse al iniciar.|Los archivos están incompletos o no se reconocen. Comprueba los archivos de Workshop; puede ser necesario descargarlos de nuevo.|Este Mod incluye funciones de juego que deben cargarse al iniciar.".Split('|'),
        ["spa"] = "Reinicio necesario en la primera carga|Se revisará después de descargar|Reinicia para cargar este aspecto|Suscrito: {0}.\n{1}\nReinicia el juego antes de usarlo.|Aspecto no disponible|Suscrito: {0}.\n{1}\nReiniciar no basta. Elige un aspecto compatible con tu versión del juego.|Este aspecto incluye funciones que deben cargarse al iniciar.|Falta un Mod necesario o su versión no es compatible. Instala y activa primero una versión compatible.|Este aspecto requiere otra versión del juego.|Los requisitos de versión deben revisarse al iniciar el juego.|No se puede cargar todo el contenido del aspecto en esta sesión.|Cambiaron archivos cargados. Reinicia para no mezclar recursos anteriores y nuevos.|Ya existe un Mod con el mismo ID; su carga debe resolverse al iniciar.|Los archivos están incompletos o no se reconocen. Revisa los archivos de Workshop; puede ser necesario descargarlos otra vez.|Este Mod incluye funciones de juego que deben cargarse al iniciar.".Split('|'),
        ["fra"] = "Redémarrage requis au premier chargement|Vérification après téléchargement|Redémarrez pour charger cette apparence|Abonnement : {0}.\n{1}\nRedémarrez le jeu avant de l’utiliser.|Apparence indisponible|Abonnement : {0}.\n{1}\nRedémarrer ne suffira pas. Choisissez une apparence adaptée à votre version du jeu.|Cette apparence comporte des fonctions à charger au démarrage.|Un Mod requis est absent ou incompatible. Installez et activez une version compatible.|Cette apparence exige une autre version du jeu.|Le jeu doit vérifier les exigences de version au démarrage.|Le contenu complet de cette apparence ne peut pas être chargé pendant cette session.|Des fichiers chargés ont changé. Redémarrez pour éviter de mélanger anciennes et nouvelles ressources.|Un Mod avec le même ID existe déjà ; son chargement doit être résolu au démarrage.|Fichiers incomplets ou non reconnus. Vérifiez les fichiers du Workshop ; un nouveau téléchargement peut être nécessaire.|Ce Mod contient des fonctions de jeu à charger au démarrage.".Split('|'),
        ["ita"] = "Riavvio necessario al primo caricamento|Verifica dopo il download|Riavvia per caricare questo aspetto|Iscrizione: {0}.\n{1}\nRiavvia il gioco prima di usarlo.|Aspetto non disponibile|Iscrizione: {0}.\n{1}\nRiavviare non basta. Scegli un aspetto compatibile con la tua versione del gioco.|Questo aspetto include funzioni da caricare all’avvio.|Un Mod richiesto non è caricato o è incompatibile. Installa e attiva prima una versione compatibile.|Questo aspetto richiede un’altra versione del gioco.|I requisiti di versione devono essere verificati all’avvio del gioco.|Non è possibile caricare tutti i contenuti dell’aspetto in questa sessione.|I file caricati sono cambiati. Riavvia per non mescolare risorse vecchie e nuove.|Esiste già un Mod con lo stesso ID; il caricamento va risolto all’avvio.|File incompleti o non riconosciuti. Controlla i file del Workshop; potrebbe servire un nuovo download.|Questo Mod include funzioni di gioco da caricare all’avvio.".Split('|'),
        ["jpn"] = "初回の読み込みには再起動が必要|ダウンロード後に即時読み込みを確認|再起動してスキンを読み込み|登録済み：{0}。\n{1}\n使用前にゲームを再起動してください。|スキンを利用できません|登録済み：{0}。\n{1}\n再起動だけでは解決しません。現在のゲームバージョンに対応するスキンを選んでください。|このスキンには起動時に読み込む必要のある機能があります。|必須 Mod が未読み込み、またはバージョンが非対応です。対応する前提 Mod をインストールして有効にしてください。|このスキンは別のゲームバージョンを必要とします。|ゲーム起動時にバージョン要件の確認が必要です。|今回の起動中にスキンの全内容を読み込むことはできません。|読み込み済みのファイルが変更されました。新旧リソースの混在を避けるため再起動してください。|同じ ID の Mod が存在するため、起動時に読み込み関係を処理する必要があります。|ファイルが不完全、または認識できません。ワークショップのファイルを確認し、必要なら再ダウンロードしてください。|この Mod には起動時に読み込む必要のあるゲーム機能が含まれます。".Split('|'),
        ["kor"] = "첫 로딩 시 재시작 필요|다운로드 후 즉시 로딩 지원 확인|스킨을 불러오려면 재시작 필요|구독 완료: {0}.\n{1}\n사용하기 전에 게임을 재시작하세요.|스킨 사용 불가|구독 완료: {0}.\n{1}\n재시작만으로는 해결되지 않습니다. 현재 게임 버전에 맞는 스킨을 선택하세요.|이 스킨에는 게임 시작 시 불러와야 하는 기능이 있습니다.|필수 Mod가 로딩되지 않았거나 버전이 맞지 않습니다. 호환되는 선행 Mod를 설치하고 활성화하세요.|이 스킨은 다른 게임 버전이 필요합니다.|게임 시작 시 스킨의 버전 요구 사항을 확인해야 합니다.|이번 실행 중에는 스킨의 모든 내용을 불러올 수 없습니다.|로딩된 파일이 변경되었습니다. 이전 리소스와 새 리소스가 섞이지 않도록 재시작하세요.|같은 ID의 Mod가 이미 있어 시작 시 로딩 관계를 처리해야 합니다.|파일이 불완전하거나 인식되지 않습니다. 창작마당 파일을 확인하고 필요하면 다시 다운로드하세요.|이 Mod에는 게임 시작 시 불러와야 하는 게임플레이 기능이 있습니다.".Split('|'),
        ["pol"] = "Pierwsze wczytanie wymaga restartu|Sprawdzenie po pobraniu|Uruchom ponownie, aby wczytać skórkę|Subskrybowano: {0}.\n{1}\nUruchom grę ponownie przed użyciem.|Skórka niedostępna|Subskrybowano: {0}.\n{1}\nSam restart nie pomoże. Wybierz skórkę zgodną z wersją gry.|Ta skórka zawiera funkcje wczytywane przy uruchomieniu gry.|Brak wymaganego Moda lub jego wersja jest niezgodna. Zainstaluj i włącz zgodną wersję.|Ta skórka wymaga innej wersji gry.|Wymagania wersji muszą zostać sprawdzone przy uruchomieniu gry.|Nie można wczytać całej zawartości skórki w tej sesji.|Wczytane pliki zmieniły się. Uruchom grę ponownie, aby nie mieszać zasobów.|Mod o tym samym ID już istnieje; jego wczytanie trzeba rozstrzygnąć przy uruchomieniu.|Pliki są niekompletne lub nierozpoznane. Sprawdź pliki Warsztatu; może być potrzebne ponowne pobranie.|Ten Mod zawiera funkcje rozgrywki wczytywane przy uruchomieniu.".Split('|'),
        ["ptb"] = "Primeiro carregamento exige reinício|Verificação após baixar|Reinicie para carregar esta aparência|Inscrito: {0}.\n{1}\nReinicie o jogo antes de usar.|Aparência indisponível|Inscrito: {0}.\n{1}\nSó reiniciar não resolve. Escolha uma aparência compatível com sua versão do jogo.|Esta aparência inclui funções que precisam carregar na inicialização.|Um Mod obrigatório não foi carregado ou é incompatível. Instale e ative uma versão compatível.|Esta aparência exige outra versão do jogo.|Os requisitos de versão precisam ser verificados na inicialização.|Não é possível carregar todo o conteúdo desta aparência nesta sessão.|Arquivos carregados mudaram. Reinicie para não misturar recursos antigos e novos.|Já existe um Mod com o mesmo ID; o carregamento precisa ser resolvido na inicialização.|Arquivos incompletos ou não reconhecidos. Confira os arquivos da Oficina; pode ser necessário baixar novamente.|Este Mod inclui funções de jogo que precisam carregar na inicialização.".Split('|'),
        ["rus"] = "Первая загрузка требует перезапуска|Проверка после скачивания|Перезапустите для загрузки облика|Подписка оформлена: {0}.\n{1}\nПерезапустите игру перед использованием.|Облик недоступен|Подписка оформлена: {0}.\n{1}\nПерезапуск не поможет. Выберите облик для вашей версии игры.|Этот облик содержит функции, загружаемые при запуске игры.|Нужный мод не загружен или несовместим. Установите и включите совместимую версию.|Этот облик требует другую версию игры.|Требования к версии должны быть проверены при запуске игры.|Невозможно загрузить всё содержимое облика в текущем сеансе.|Загруженные файлы изменились. Перезапустите игру, чтобы не смешивать старые и новые ресурсы.|Мод с таким ID уже существует; порядок загрузки нужно определить при запуске.|Файлы неполные или не распознаны. Проверьте файлы Мастерской; возможно, нужно скачать заново.|Этот мод содержит игровые функции, загружаемые при запуске.".Split('|'),
        ["tha"] = "การโหลดครั้งแรกต้องเริ่มเกมใหม่|ตรวจสอบหลังดาวน์โหลด|เริ่มเกมใหม่เพื่อโหลดสกิน|สมัครแล้ว: {0}\n{1}\nกรุณาเริ่มเกมใหม่ก่อนใช้งาน|ยังใช้สกินไม่ได้|สมัครแล้ว: {0}\n{1}\nเริ่มเกมใหม่อย่างเดียวแก้ไม่ได้ โปรดเลือกสกินที่รองรับเวอร์ชันเกมปัจจุบัน|สกินนี้มีฟังก์ชันที่ต้องโหลดเมื่อเริ่มเกม|Mod ที่จำเป็นยังไม่โหลดหรือเวอร์ชันไม่ตรง โปรดติดตั้งและเปิดใช้เวอร์ชันที่รองรับก่อน|สกินนี้ต้องใช้เกมอีกเวอร์ชันหนึ่ง|ต้องตรวจสอบข้อกำหนดเวอร์ชันเมื่อเริ่มเกม|ไม่สามารถโหลดเนื้อหาสกินทั้งหมดในการเปิดเกมครั้งนี้ได้|ไฟล์ที่โหลดมีการเปลี่ยนแปลง โปรดเริ่มเกมใหม่เพื่อไม่ให้ทรัพยากรเก่าและใหม่ปะปนกัน|มี Mod ที่ใช้ ID เดียวกันอยู่แล้ว ต้องจัดการลำดับโหลดเมื่อเริ่มเกม|ไฟล์ไม่ครบหรือไม่รู้จักรูปแบบ โปรดตรวจสอบไฟล์เวิร์กชอป อาจต้องดาวน์โหลดใหม่|Mod นี้มีฟังก์ชันการเล่นที่ต้องโหลดเมื่อเริ่มเกม".Split('|'),
        ["tur"] = "İlk yükleme yeniden başlatma gerektirir|İndirmeden sonra kontrol edilir|Görünümü yüklemek için yeniden başlatın|Abone olundu: {0}.\n{1}\nKullanmadan önce oyunu yeniden başlatın.|Görünüm kullanılamıyor|Abone olundu: {0}.\n{1}\nYeniden başlatmak yetmez. Oyun sürümünüzle uyumlu bir görünüm seçin.|Bu görünüm, oyun açılışında yüklenmesi gereken özellikler içeriyor.|Gerekli bir Mod yüklenmemiş veya sürümü uyumsuz. Önce uyumlu bağımlılığı kurup etkinleştirin.|Bu görünüm başka bir oyun sürümü gerektiriyor.|Sürüm gereksinimleri oyun açılışında kontrol edilmelidir.|Bu görünümün tüm içeriği mevcut oturumda yüklenemiyor.|Yüklü dosyalar değişti. Eski ve yeni kaynakların karışmaması için yeniden başlatın.|Aynı kimliğe sahip bir Mod zaten var; yükleme sırası açılışta çözülmelidir.|Dosyalar eksik veya tanınmıyor. Atölye dosyalarını kontrol edin; tekrar indirmek gerekebilir.|Bu Mod, oyun açılışında yüklenmesi gereken oynanış özellikleri içeriyor.".Split('|')
    };
    public static string Get(WorkshopNoticeKey key) => ForLanguage(ModLocalization.CurrentLanguage, key);
    public static string ForLanguage(string language, WorkshopNoticeKey key) => Packs.GetValueOrDefault(language, Packs["eng"])[(int)key];
    public static string Reason(WorkshopLoadReason reason) => Get(reason switch
    {
        WorkshopLoadReason.StartupCode => WorkshopNoticeKey.Startup,
        WorkshopLoadReason.Dependency => WorkshopNoticeKey.Dependency,
        WorkshopLoadReason.Version => WorkshopNoticeKey.Version,
        WorkshopLoadReason.VersionRule => WorkshopNoticeKey.UnknownRule,
        WorkshopLoadReason.ChangedFiles => WorkshopNoticeKey.Changed,
        WorkshopLoadReason.DuplicateId => WorkshopNoticeKey.Duplicate,
        WorkshopLoadReason.InvalidPackage => WorkshopNoticeKey.Invalid,
        WorkshopLoadReason.Gameplay => WorkshopNoticeKey.Gameplay,
        _ => WorkshopNoticeKey.Incomplete
    });
}
